<a href="https://colab.research.google.com/github/Saturn-space/Saturn-space/blob/Python/9.%20Numpy_Playing%20with%20arrays%20(24_02_2026).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1. Create a three Dimensional array (2,2,3).

import numpy as np
a = np.array([
    [[1,2,33],[3,4,44]],
    [[5,6,66],[8,9,99]]
    ])
#a. Display the array
print(a,"\n")

#b. find shape, size and  dimensions
print("The shape is = ", np.shape(a))
print("The size is = ",np.size(a))
print("The dimension is = ",np.ndim(a))

#c. Acces one element using index
print("lets print 66 = ",a[1,0,2])
print("lets print 2 = ",a[0,0,1])

[[[ 1  2 33]
  [ 3  4 44]]

 [[ 5  6 66]
  [ 8  9 99]]] 

The shape is =  (2, 2, 3)
The size is =  12
The dimension is =  3
lets print 66 =  66
lets print 2 =  2


In [ ]:
#2. Write a python program using numpy to

#a. create Two matrix:
mat1 =  np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

mat2 =  np.array([
    [7,8,9],
    [10,11,12],
    [13,14,15]
])

print(mat1,"\n")
print(mat2)

#b. perform matrix addition, subtraction, multiplication and transpose of the matrix:
print("\nAddition of two matrices : \n", mat1+mat2)
print("\nSubtraction of two matrices : \n", mat1-mat2)
print("\nMultiplication of two matrices :\n",np.dot(mat1,mat2))
print("\ntranspose of matrix 1  : \n",np.transpose(mat1))
print("\ntranspose of matrix 2  : \n",np.transpose(mat2))


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

Addition of two matrices : 
 [[ 8 10 12]
 [14 16 18]
 [20 22 24]]

Subtraction of two matrices : 
 [[-6 -6 -6]
 [-6 -6 -6]
 [-6 -6 -6]]

Multiplication of two matrices :
 [[ 66  72  78]
 [156 171 186]
 [246 270 294]]

transpose of matrix 1  : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

transpose of matrix 2  : 
 [[ 7 10 13]
 [ 8 11 14]
 [ 9 12 15]]


In [ ]:
#3. Write a python program using numpy to analyse student marks:
#a. Store marks of 5 student  in 3 subjects

marks = np.array([
    [33,44,55],
    [66,22,44],
    [77,33,99],
    [65,35,75],
    [88,44,33],
])

#b. Find
# b(i). total marks, average marks of each student
print("Total Marks of each student is : \n", np.sum(marks,axis=1))
print("\nTotal Marks of all the student in each subject : \n", np.sum(marks,axis=0))
print("\nAverage Marks of each student is : \n", np.average(marks,axis=1))
print("\nAverage Marks of each student is : \n", np.mean(marks,axis=1))

#b(ii). highest marks in each subject:
print("\nHighest marks in each subject : \n",np.max(marks,axis=0))

#b(iii). Overall Average of the class
print("\nOverall Class Average: \n",np.sum((np.average(marks,axis=1)))/5)
print("\nOverall Class Average: \n",np.average((np.average(marks,axis=1))))


Total Marks of each student is : 
 [132 132 209 175 165]

Total Marks of all the student in each subject : 
 [329 178 306]

Average Marks of each student is : 
 [44.         44.         69.66666667 58.33333333 55.        ]

Average Marks of each student is : 
 [44.         44.         69.66666667 58.33333333 55.        ]

Highest marks in each subject : 
 [88 44 99]

Overall Class Average: 
 54.2

Overall Class Average: 
 54.2


In [11]:
arr_1d = np.array([1,2,3,4,5])
arr_copy = arr_1d.copy()
arr_view = arr_1d.view()
print("Orginal array : ", arr_1d)
print("........................")
print("copy array : ", arr_copy)
print("view array : ", arr_view)

arr_1d[0]=90
print("\nOrginal array after change : ", arr_1d)
print("........................")
print("copy array after change: ", arr_copy)
print("view array after change: ", arr_view)


Orginal array :  [1 2 3 4 5]
........................
copy array :  [1 2 3 4 5]
view array :  [1 2 3 4 5]

Orginal array after change :  [90  2  3  4  5]
........................
copy array after change:  [1 2 3 4 5]
view array after change:  [90  2  3  4  5]


In [10]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print(arr[:,:,:])
print("............................")
print(arr[1,:,1])
print("............................")
print(arr[:,1,:])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
............................
[ 8 11]
............................
[[ 4  5  6]
 [10 11 12]]
